owner: pdroll
repo: upptime
user-agent: pdroll

sites:
  - name: Garage App API
    url: $GARAGE_API_URL
    icon: https://home.pdroll.com/icon.png

status-website:
  baseUrl: /upptime
  logoUrl: https://home.pdroll.com/icon.png
  name: Garage App Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Uptime monitoring for the Garage App
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

assignees:
  - pdroll
